from . import organisation
from . import res_company
from . import coaches
from . import venues
from . import athletes
from . import parents
from . import fans
from . import athlete_groups
from . import discipline
from . import res_partner
from . import chathub
from . import res_config_settings
from . import vehicle_reg
from . import event_registration
from . import product
