# -*- coding: utf-8 -*-

{
    'name': "Organisation",
    'version': "15.0.1.0.0",
    'summary': """ Organisation """,
    'description': """ Organisation Management """,
    'author': "Ljutzkanov Ltd",
    'company': "Ljutzkanov Ltd",
    'maintainer': "Ljutzkanov Ltd",
    'website': "https://www.ljutzkanov.ltd/",
    'category': 'Tools',
    'depends': ['base', 'web', 'contacts', 'product', 'portal', 'website',
                'formio', 'sale_management', 'calendar', 'project',
                'hr', 'survey', 'hr_attendance', 'sh_all_in_one_pms',
                'event_extension'],
    'data': [
        'security/organisation_security.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/organisation_views.xml',
        'views/coaches_views.xml',
        'views/venues_views.xml',
        'views/athletes_views.xml',
        'views/parents_views.xml',
        'views/fans_views.xml',
        'views/athlete_groups_views.xml',
        'views/discipline_views.xml',
        'views/chat_hub_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/vehicle_reg_views.xml',
        'views/menu_items.xml',
        # 'views/assets.xml',
        'views/portal_templates.xml',
        'views/athletes_list_templates.xml',
        'views/dashboard_templates.xml',
        'views/dashboard_calendar_templates.xml',
        'views/edit_template.xml',
        'views/coach_dashboard_templates.xml',
        'views/parent_dashboard_templates.xml',
        'views/attendance_templates.xml',
        'views/fan_dashboard_templates.xml',
        'views/event_registration.xml',
        'views/organisation_package.xml',
        'views/website_template.xml',
        'wizard/create_athlete_views.xml',
        'wizard/create_parent_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'organisation/static/src/xml/assets_backend.xml',
            'organisation/static/src/css/backend.css',
        ],
        'web.assets_frontend': [
            'organisation/static/src/xml/assets_frontend.xml',
            'organisation/static/src/css/organisation.css',
            'organisation/static/src/js/website_sale.js',
            'organisation/static/src/js/calendar_div.js',
        ],
    },
    'qweb': [
        'static/src/xml/attendance.xml'
    ],
    'images': [],
    'license': "AGPL-3",
    'installable': True,
    'application': True
}
