# -*- coding: utf-8 -*-
{
    'name': "SaltFun Backend Theme",
    'summary': """
        Saltfun Backend Theme.
    """,
    'description': """
        Using the Arch Backend Theme, this module applies the Saltfun default branding configuration:
        1. login page + remove 'Powered by Odoo' and 'Superuser' login button
        2. backend (admin) panel
        3. frontend (customer portal) view
        4. favicon
        5. web title
    """,
    'author': "Zenman Ltd.",
    'website': "https://www.saltfun.com",
    'license': 'LGPL-3',
    'version': '15.0.1.0.8',
    'category': 'Themes/Backend',
    'depends': [
        'web',
        'base_setup',
        'mail',
        'auth_signup',
        'portal',
        'im_livechat',
    ],

    # always loaded
    'data': [
        'data/data.xml',
        'data/pl_drawer_colors.xml',
        'data/pl_color_theme.xml',
        'security/ir.model.access.csv',
        'security/curved_theme_security.xml',
        'views/views.xml',
        'views/pl_main_panel.xml',
        'views/templates.xml',
        'views/pl_assets_popup_animation.xml',
        'views/pl_login_page.xml',
        'views/pl_res_users_preferences.xml',
        'views/pl_res_config_settings_view.xml',
        'data/saltfun_pwa_configuration.xml',
        'data/saltfun_default_favicon.xml',
        'data/saltfun_default_company_logo.xml',
        'views/saltfun_favicon_extend.xml',
        'views/saltfun_login_page_extend.xml',
        'views/saltfun_portal_template_extend.xml',
    ],
    'images': [
        'static/description/Banner.jpg',
        'static/description/list_screenshot.gif',
    ],
    'assets': {
        'web.assets_qweb': [
            '/pl_curved_backend_theme/static/src/xml/pl_menu.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_left_sidebar_panel.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_switch_language.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_quick_settings.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_global_settings.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_fullscreen.xml',
            # '/pl_curved_backend_theme/static/src/xml/pl_search_panel.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_company_settings.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_bookmark.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_appdrawer_edit.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_calendar_view.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_image_template.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_login_background_color.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_login_background_image.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_menubar_darkmode_toggle.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_leftpanelmenu.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_userMenu.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_navbar.xml',
            '/pl_curved_backend_theme/static/src/xml/pl_action_menus.xml',
            '/pl_curved_backend_theme/static/src/js/widgets/plListDocumentViewer.xml',
            # '/pl_curved_backend_theme/static/src/xml/Pl_throbber_inherit.xml',
        ],
        'web._assets_primary_variables': [
            '/pl_curved_backend_theme/static/src/scss/abstracts/odoo_primary_variables.scss',
        ],
        'web.assets_backend': [
            '/pl_curved_backend_theme/static/src/scss/abstracts/variables.scss',
            '/pl_curved_backend_theme/static/src/scss/base/fonts.scss',
            '/pl_curved_backend_theme/static/src/scss/base/default.scss',
            '/pl_curved_backend_theme/static/src/scss/base/animation.scss',
            '/pl_curved_backend_theme/static/src/scss/base/forms.scss',
            '/pl_curved_backend_theme/static/src/scss/base/fields.scss',
            '/pl_curved_backend_theme/static/src/scss/abstracts/mixins.scss',
            '/pl_curved_backend_theme/static/src/scss/abstracts/placeholder.scss',
            '/pl_curved_backend_theme/static/src/scss/components/buttons.scss',
            '/pl_curved_backend_theme/static/src/scss/components/color_theme.scss',
            '/pl_curved_backend_theme/static/src/scss/components/tabs.scss',
            '/pl_curved_backend_theme/static/src/scss/components/table.scss',
            '/pl_curved_backend_theme/static/src/scss/components/form-control.scss',
            '/pl_curved_backend_theme/static/src/scss/components/checkbox.scss',
            '/pl_curved_backend_theme/static/src/scss/components/loaders.scss',
            '/pl_curved_backend_theme/static/src/scss/components/Breadcrumb.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/header.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/apps-drawer.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/pl_quick_settings.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/sidebar.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/bookmark.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/pl_control_panel.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/pl_form_view.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/pl_view.scss',
            '/pl_curved_backend_theme/static/src/scss/layout/pl_vertical_menus.scss',
            '/pl_curved_backend_theme/static/src/scss/responsive/ipad_responsive.scss',
            '/pl_curved_backend_theme/static/src/scss/responsive/phone_responsive.scss',
            '/pl_curved_backend_theme/static/src/scss/pages/discuss.scss',
            '/pl_curved_backend_theme/static/src/scss/pages/calendar.scss',
            '/pl_curved_backend_theme/static/src/scss/pages/all_apps.scss',
            '/pl_curved_backend_theme/static/src/lib/owl.carousel.min.css',

            # js assets
            '/pl_curved_backend_theme/static/src/Components/pl_dropdown_menu.js',
            '/pl_curved_backend_theme/static/src/Components/Pl_custom_action_menu.js',
            '/pl_curved_backend_theme/static/src/js/Pl_control_panel_inherit.js',
            '/pl_curved_backend_theme/static/src/js/pl_searchbar.js',
            '/pl_curved_backend_theme/static/src/js/Pl_controlpanel_view.js',
            '/pl_curved_backend_theme/static/src/js/splitview/PlAbstractControllerInherit.js',
            '/pl_curved_backend_theme/static/src/js/widgets/plListDocumentViewer.js',
            # '/pl_curved_backend_theme/static/src/js/splitview/PlActionManagerInherit.js',
            '/pl_curved_backend_theme/static/src/js/PlWebFrameWork_inherit.js',
            '/pl_curved_backend_theme/static/src/js/pl_app_sidebar.js',
            '/pl_curved_backend_theme/static/src/js/pl_left_sidebar_panel.js',
            '/pl_curved_backend_theme/static/src/js/pl_switch_language.js',
            '/pl_curved_backend_theme/static/src/js/pl_darkmode_toggle.js',
            '/pl_curved_backend_theme/static/src/js/pl_bookmarpl_menu.js',
            '/pl_curved_backend_theme/static/src/js/pl_quick_settings_widget.js',
            '/pl_curved_backend_theme/static/src/js/pl_appsmenu.js',
            '/pl_curved_backend_theme/static/src/js/pl_fullscreen.js',
            '/pl_curved_backend_theme/static/src/js/pl_search_panel.js',
            '/pl_curved_backend_theme/static/src/js/views/list/pl_list_renderer.js',
            '/pl_curved_backend_theme/static/src/js/views/form/pl_form_render.js',
            '/pl_curved_backend_theme/static/src/js/pl_global_config_widget.js',
            '/pl_curved_backend_theme/static/src/js/pl_company_config_widget.js',
            '/pl_curved_backend_theme/static/src/js/pl_appdrawer_edit.js',
            '/pl_curved_backend_theme/static/src/js/pl_click_to_edit.js',
            '/pl_curved_backend_theme/static/src/js/pl_abstract_web_client.js',
            '/pl_curved_backend_theme/static/src/js/pl_data_manager.js',
            '/pl_curved_backend_theme/static/src/js/pl_zoom_btn_visibility.js',
            '/pl_curved_backend_theme/static/src/js/pl_calendar_view.js',
            '/pl_curved_backend_theme/static/src/js/pl_relation_fields.js',
            '/pl_curved_backend_theme/static/src/js/views/form/pl_form_controller.js',
            '/pl_curved_backend_theme/static/src/js/views/list/pl_list_controller.js',
            '/pl_curved_backend_theme/static/src/js/plAbstractController.js',
            '/pl_curved_backend_theme/static/src/js/views/kanban/pl_kanban_controller_inherit.js',
            #'/pl_curved_backend_theme/static/src/js/views/graph/pl_graph_controller_inherit.js',
            # '/pl_curved_backend_theme/static/src/js/views/pivot/pl_pivot_controller_inherit.js',
            '/pl_curved_backend_theme/static/src/js/views/calendar/pl_calendar_controller_inherit.js',
            '/pl_curved_backend_theme/static/src/lib/owl.carousel.min.js',
            '/pl_curved_backend_theme/static/src/js/app.js',
            '/pl_curved_backend_theme/static/src/js/sw.js',
        ],
        'web.assets_frontend': [
            '/pl_curved_backend_theme/static/src/scss/pages/pl_login.scss',
            '/pl_curved_backend_theme/static/src/scss/base/fonts.scss',
            '/pl_curved_backend_theme/static/src/scss/saltfun/saltfun_assets_frontend.scss',
            ('after', '/portal/static/src/scss/portal.scss',
             '/pl_curved_backend_theme/static/src/scss/saltfun/saltfun_assets_portal.scss'),
            '/pl_curved_backend_theme/static/src/scss/saltfun/saltfun_overwrite_primary_vars.scss',
        ],

    },

    "application": True,
    "installable": True,
}
